### ISSUE TITLE
Add imagedraw

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/LibLathe#39]
Investigate and add imagedraw.

https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html

**Acceptance criteria**

- Draw paths
- Class based (Class in the library called LLPlot with a method called get backplot)
- Works with example
- Set the background colour
- Automatically calculate image size
- Set G path color
- Set the line thickness

**Comment by Brett-Parker** [comment]
@dubstar-04 can you add some information/sketches of what sort of thing your looking for.

**Comment by dubstar-04** [comment]
@Brett-Parker 

I think a really helpful feature would be to produce a backplot like the image below. 

![backplot](https://user-images.githubusercontent.com/1136710/96166901-84676d80-0f16-11eb-81f2-29e751f15e7a.png)

This would help visualise the part, stock and generated path.

**Comment by Brett-Parker** [comment]
Add ability to;

1. Plotting only rapid (G0)
2. Plotting only cutting moves (G1, 2 and 3)
3. Set the background colour
4. Set the line thickness
