### ISSUE TITLE
Enhance imagedraw capabilities

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/LibLathe#50]
Add to current imagedraw functionality

1. Plotting only rapid (G0)
2. Plotting only cutting moves (G1, 2 and 3)
3. Handle other than lines (G2/G3)

**Comment by Brett-Parker** [comment]
@dubstar-04 can you explain what each G should be and what we need to draw.

For example G0/1 draw line - it does xyz...

**Comment by Brett-Parker** [comment]
For understanding G02/G03: https://www.cnccookbook.com/cnc-g-code-arc-circle-g02-g03/

Need an example .gcode file with G02/G03.

**Comment by dubstar-04** [comment]
@Brett-Parker It would be really helpful if LLPlot could accept Segments and SegmentGroups and plot the geometry to aid visualisation and debugging.
