### ISSUE TITLE
Review license

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/LibLathe#57]
Review license suitability.

**Comment by dubstar-04** [comment]
Recommended license is LGPL to allow LibLathe to be shipped with most opensource software.

Need to review what the difference is between LGPL and GPL.

**Comment by Brett-Parker** [comment]
https://en.m.wikipedia.org/wiki/GNU_Lesser_General_Public_License#:~:text=dropped%20these%20terms.-,Differences%20from%20the%20GPL,free%20software%20or%20proprietary%20software.

**Comment by dubstar-04** [comment]
Leaving the license for now. reopen if this presents an issue later.
