### ISSUE TITLE
I cannot load it

### ISSUE THREAD

**Issue by Attigliuzzo** [dubstar-04/LibLathe#6]
I'm trying to load your lib on my debian testing machine with FreeCad 0.18.4. I copied the whole folder in my mod directory then i type in the python console:

`import LibLathe`

without errors, but i cannot find it anywhere. Thanks

**Comment by dubstar-04** [comment]
Please see the FreeCAD Turning addon here https://github.com/dubstar-04/FreeCAD_Turning_Addon
